ADMIN_PASSWORD = "sanjar1989"
USER_PASSWORD = "ilmiymarkaz"
SUPABASE_URL = "https://awhzayyzskacfcqtldjy.supabase.co"
SUPABASE_KEY = "sb_secret_dTE16vKsYYcjPyNKJE-Ykg_HDW9mog5"
SUPABASE_BUCKET = "etranzit-data"